export const mockTreasuryData = {
  rings: {
    "ring-1": {
      balance: 15750,
      totalDeposits: 25000,
      totalWithdrawals: 9250,
      memberRatios: [
        {
          userId: "user-1",
          totalContributed: 8000,
          ratio: 32,
          withdrawalLimit: 5040,
        },
        {
          userId: "user-2",
          totalContributed: 6500,
          ratio: 26,
          withdrawalLimit: 4095,
        },
        {
          userId: "user-3",
          totalContributed: 5500,
          ratio: 22,
          withdrawalLimit: 3465,
        },
        {
          userId: "user-4",
          totalContributed: 3000,
          ratio: 12,
          withdrawalLimit: 1890,
        },
        {
          userId: "user-5",
          totalContributed: 2000,
          ratio: 8,
          withdrawalLimit: 1260,
        },
      ],
      transactions: [
        {
          id: "txn-1",
          userId: "user-1",
          type: "deposit",
          amount: 2000,
          purpose: "Monthly contribution",
          status: "approved",
          timestamp: "2024-01-15T10:30:00Z",
        },
        {
          id: "txn-2",
          userId: "user-2",
          type: "withdrawal",
          amount: 800,
          purpose: "Community garden supplies",
          status: "approved",
          timestamp: "2024-01-14T16:45:00Z",
        },
        {
          id: "txn-3",
          userId: "user-3",
          type: "deposit",
          amount: 1500,
          purpose: "Emergency fund contribution",
          status: "approved",
          timestamp: "2024-01-14T12:20:00Z",
        },
        {
          id: "txn-4",
          userId: "user-4",
          type: "withdrawal",
          amount: 1200,
          purpose: "Community event expenses",
          status: "pending",
          timestamp: "2024-01-13T19:15:00Z",
        },
        {
          id: "txn-5",
          userId: "user-1",
          type: "withdrawal",
          amount: 500,
          purpose: "Tool library maintenance",
          status: "approved",
          timestamp: "2024-01-12T14:30:00Z",
        },
      ],
    },
    "ring-2": {
      balance: 8900,
      totalDeposits: 12000,
      totalWithdrawals: 3100,
      memberRatios: [
        {
          userId: "user-6",
          totalContributed: 4000,
          ratio: 33,
          withdrawalLimit: 2937,
        },
        {
          userId: "user-7",
          totalContributed: 3500,
          ratio: 29,
          withdrawalLimit: 2581,
        },
        {
          userId: "user-8",
          totalContributed: 2500,
          ratio: 21,
          withdrawalLimit: 1869,
        },
        {
          userId: "user-9",
          totalContributed: 2000,
          ratio: 17,
          withdrawalLimit: 1513,
        },
      ],
      transactions: [
        {
          id: "txn-6",
          userId: "user-6",
          type: "deposit",
          amount: 1000,
          purpose: "Startup contribution",
          status: "approved",
          timestamp: "2024-01-10T11:30:00Z",
        },
      ],
    },
  },
  families: {
    "family-1": {
      balance: 3200,
      totalDeposits: 4500,
      totalWithdrawals: 1300,
      memberRatios: [
        {
          userId: "user-1",
          totalContributed: 2000,
          ratio: 44,
          withdrawalLimit: 1408,
        },
        {
          userId: "user-2",
          totalContributed: 1500,
          ratio: 33,
          withdrawalLimit: 1056,
        },
        {
          userId: "user-3",
          totalContributed: 1000,
          ratio: 23,
          withdrawalLimit: 736,
        },
      ],
      transactions: [
        {
          id: "fam-txn-1",
          userId: "user-1",
          type: "deposit",
          amount: 800,
          purpose: "Monthly household fund",
          status: "approved",
          timestamp: "2024-01-15T09:00:00Z",
        },
        {
          id: "fam-txn-2",
          userId: "user-2",
          type: "withdrawal",
          amount: 120,
          purpose: "Groceries for the week",
          status: "approved",
          timestamp: "2024-01-14T18:30:00Z",
        },
        {
          id: "fam-txn-3",
          userId: "user-3",
          type: "withdrawal",
          amount: 80,
          purpose: "Utilities payment",
          status: "approved",
          timestamp: "2024-01-13T15:45:00Z",
        },
        {
          id: "fam-txn-4",
          userId: "user-1",
          type: "withdrawal",
          amount: 200,
          purpose: "Family dinner out",
          status: "approved",
          timestamp: "2024-01-12T19:20:00Z",
        },
        {
          id: "fam-txn-5",
          userId: "user-2",
          type: "deposit",
          amount: 500,
          purpose: "Bonus contribution",
          status: "approved",
          timestamp: "2024-01-11T12:15:00Z",
        },
      ],
    },
    "family-2": {
      balance: 1850,
      totalDeposits: 2200,
      totalWithdrawals: 350,
      memberRatios: [
        {
          userId: "user-4",
          totalContributed: 1200,
          ratio: 55,
          withdrawalLimit: 1018,
        },
        {
          userId: "user-5",
          totalContributed: 1000,
          ratio: 45,
          withdrawalLimit: 833,
        },
      ],
      transactions: [
        {
          id: "fam-txn-6",
          userId: "user-4",
          type: "deposit",
          amount: 600,
          purpose: "Initial family fund",
          status: "approved",
          timestamp: "2024-01-08T14:00:00Z",
        },
      ],
    },
  },
}
