import type { Resource, Skill } from "./types"

export const mockResources: Resource[] = [
  {
    id: "resource1",
    name: "Professional Camera",
    description: "Canon EOS 5D Mark IV with 24-70mm lens",
    category: "Electronics",
    ownerId: "user1",
    createdAt: "2023-01-15T10:30:00Z",
    tags: ["photography", "equipment", "camera"],
    image: "/vintage-record-player.png",
  },
  {
    id: "resource2",
    name: "Garden Tools Set",
    description: "Complete set of gardening tools including shovel, rake, pruners, and gloves",
    category: "Gardening",
    ownerId: "user2",
    createdAt: "2023-02-20T14:45:00Z",
    tags: ["gardening", "tools", "outdoor"],
    image: "/lush-garden.png",
  },
  {
    id: "resource3",
    name: "Portable Projector",
    description: "HD projector with Bluetooth speaker, perfect for outdoor movie nights",
    category: "Electronics",
    ownerId: "user3",
    createdAt: "2023-03-05T09:15:00Z",
    tags: ["entertainment", "projector", "movie"],
    image: "/web-development-concept.png",
  },
  {
    id: "resource4",
    name: "Electric Drill",
    description: "Cordless power drill with various bits and attachments",
    category: "Tools",
    ownerId: "user1",
    createdAt: "2023-03-10T16:20:00Z",
    tags: ["tools", "diy", "construction"],
    image: "/diverse-construction-team.png",
  },
  {
    id: "resource5",
    name: "Camping Tent",
    description: "4-person waterproof tent, easy to set up",
    category: "Outdoor",
    ownerId: "user4",
    createdAt: "2023-04-02T11:30:00Z",
    tags: ["camping", "outdoor", "tent"],
    image: "/mountain-bike-trail.png",
  },
]

export const mockSkills: Skill[] = [
  {
    id: "skill1",
    name: "Web Development",
    description: "Full-stack web development with React, Node.js, and MongoDB",
    category: "Technology",
    level: "expert",
    ownerId: "user1",
    createdAt: "2023-01-10T08:30:00Z",
    tags: ["coding", "web", "javascript"],
  },
  {
    id: "skill2",
    name: "Organic Gardening",
    description: "Sustainable gardening practices, composting, and pest management",
    category: "Gardening",
    level: "advanced",
    ownerId: "user2",
    createdAt: "2023-02-15T13:45:00Z",
    tags: ["gardening", "organic", "sustainability"],
  },
  {
    id: "skill3",
    name: "Photography",
    description: "Portrait and landscape photography, editing with Adobe Lightroom",
    category: "Creative",
    level: "intermediate",
    ownerId: "user3",
    createdAt: "2023-03-01T10:15:00Z",
    tags: ["photography", "creative", "editing"],
  },
  {
    id: "skill4",
    name: "Cooking",
    description: "Specializing in plant-based and international cuisines",
    category: "Food",
    level: "advanced",
    ownerId: "user4",
    createdAt: "2023-03-20T17:30:00Z",
    tags: ["cooking", "food", "vegan"],
  },
  {
    id: "skill5",
    name: "Carpentry",
    description: "Furniture making, woodworking, and basic home repairs",
    category: "Crafts",
    level: "intermediate",
    ownerId: "user1",
    createdAt: "2023-04-05T09:45:00Z",
    tags: ["woodworking", "diy", "furniture"],
  },
]
