import { type GroupMarketplaceListing, TransactionType } from "./types"

export const mockGroupMarketplaceListings: GroupMarketplaceListing[] = [
  {
    id: "gm1",
    title: "Gardening Tools Set",
    description:
      "Complete set of gardening tools including shovel, rake, pruners, and gloves. Perfect for community garden projects.",
    transactionType: TransactionType.Borrow,
    duration: "Up to 1 week",
    resourceId: "r1",
    sellerId: "user1",
    groupId: "1",
    createdAt: "2023-05-15T10:30:00Z",
    images: ["/gardening-tools-set.png"],
    tags: ["gardening", "tools", "community"],
    status: "available",
  },
  {
    id: "gm2",
    title: "Web Development Workshop",
    description:
      "I'm offering a free workshop on web development basics for group members. Learn HTML, CSS, and JavaScript fundamentals.",
    transactionType: TransactionType.Gift,
    skillId: "s2",
    sellerId: "user2",
    groupId: "1",
    createdAt: "2023-05-12T14:45:00Z",
    tags: ["education", "technology", "skills"],
    status: "available",
  },
  {
    id: "gm3",
    title: "Professional Camera",
    description: "Canon EOS 5D Mark IV with 24-70mm lens. Available for rent for your photography projects.",
    transactionType: TransactionType.Rent,
    price: 50,
    duration: "Daily rate",
    resourceId: "r3",
    sellerId: "user3",
    groupId: "1",
    createdAt: "2023-05-10T09:15:00Z",
    images: ["/professional-camera.png"],
    tags: ["photography", "equipment", "creative"],
    status: "available",
  },
  {
    id: "gm4",
    title: "Homemade Organic Sourdough Bread",
    description: "Fresh baked sourdough bread made with organic ingredients. Supporting our local food initiative.",
    transactionType: TransactionType.Sale,
    price: 8,
    sellerId: "user4",
    groupId: "1",
    createdAt: "2023-05-08T16:20:00Z",
    images: ["/sourdough-bread.png"],
    tags: ["food", "organic", "homemade"],
    status: "available",
  },
  {
    id: "gm5",
    title: "Graphic Design Services",
    description: "I can help with logo design, branding, and marketing materials for your projects or small business.",
    transactionType: TransactionType.Sale,
    price: 35,
    skillId: "s5",
    sellerId: "user5",
    groupId: "1",
    createdAt: "2023-05-05T11:00:00Z",
    tags: ["design", "creative", "business"],
    status: "available",
  },
  {
    id: "gm6",
    title: "Electric Drill and Bit Set",
    description: "Cordless electric drill with various bits for home improvement projects. Available to borrow.",
    transactionType: TransactionType.Borrow,
    duration: "Weekend use",
    resourceId: "r6",
    sellerId: "user6",
    groupId: "2",
    createdAt: "2023-05-03T13:30:00Z",
    images: ["/electric-drill.png"],
    tags: ["tools", "diy", "home improvement"],
    status: "available",
  },
  {
    id: "gm7",
    title: "Spanish Language Lessons",
    description: "Offering conversational Spanish lessons for beginners. Can meet in person or online.",
    transactionType: TransactionType.Gift,
    skillId: "s7",
    sellerId: "user7",
    groupId: "2",
    createdAt: "2023-05-01T15:45:00Z",
    tags: ["education", "language", "skills"],
    status: "available",
  },
  {
    id: "gm8",
    title: "Vintage Record Collection",
    description: "Selling my collection of jazz and blues vinyl records. Great condition, some rare finds included.",
    transactionType: TransactionType.Sale,
    price: 120,
    sellerId: "user8",
    groupId: "2",
    createdAt: "2023-04-28T09:00:00Z",
    images: ["/vintage-records.png"],
    tags: ["music", "collectibles", "vintage"],
    status: "available",
  },
  // Joint Venture Business Services
  {
    id: "venture-service-1",
    title: "Residential Solar Installation",
    description: "Professional solar panel installation with community cooperative pricing. 15% savings through bulk purchasing and shared resources.",
    transactionType: TransactionType.Sale,
    price: 12000,
    sellerId: "user1",
    groupId: "venture-org-1",
    createdAt: "2023-08-20T09:00:00Z",
    images: ["/renewable-energy.png"],
    tags: ["solar", "renewable-energy", "installation", "cooperative"],
    status: "available",
  },
  {
    id: "venture-service-2",
    title: "Solar System Maintenance",
    description: "Annual maintenance service for solar installations including cleaning, inspection, and performance optimization.",
    transactionType: TransactionType.Sale,
    price: 350,
    sellerId: "user3",
    groupId: "venture-org-1", 
    createdAt: "2023-09-01T10:00:00Z",
    images: ["/renewable-energy.png"],
    tags: ["solar", "maintenance", "service"],
    status: "available",
  },
  {
    id: "venture-service-3",
    title: "Local Organic Produce Box",
    description: "Weekly produce box with seasonal vegetables, fruits, and herbs from local partner farms. Community-supported agriculture.",
    transactionType: TransactionType.Sale,
    price: 45,
    duration: "Weekly subscription",
    sellerId: "user2",
    groupId: "venture-org-2",
    createdAt: "2023-09-10T11:00:00Z",
    images: ["/colorful-fruit-display.png"],
    tags: ["food", "organic", "local", "subscription"],
    status: "available",
  },
  {
    id: "venture-service-4",
    title: "Bulk Food Buying Program",
    description: "Join our cooperative bulk buying program for grains, beans, nuts, and pantry staples. Significant savings through volume purchasing.",
    transactionType: TransactionType.Sale,
    price: 25,
    duration: "Monthly membership",
    sellerId: "user4", 
    groupId: "venture-org-2",
    createdAt: "2023-10-01T12:00:00Z",
    images: ["/colorful-fruit-display.png"],
    tags: ["food", "bulk", "cooperative", "savings"],
    status: "available",
  },
  {
    id: "venture-service-5",
    title: "Creative Workspace Membership",
    description: "24/7 access to shared workspace with high-speed internet, meeting rooms, 3D printer, and collaborative work areas.",
    transactionType: TransactionType.Rent,
    price: 120,
    duration: "Monthly membership",
    sellerId: "user3",
    groupId: "venture-org-3",
    createdAt: "2023-07-25T13:00:00Z",
    images: ["/diverse-construction-team.png"],
    tags: ["workspace", "creative", "membership", "collaborative"],
    status: "available",
  },
  {
    id: "venture-service-6",
    title: "Project Collaboration Platform",
    description: "Digital platform for managing creative projects, finding collaborators, and revenue sharing. Includes booking system for workspace resources.",
    transactionType: TransactionType.Sale,
    price: 15,
    duration: "Monthly subscription",
    sellerId: "user5",
    groupId: "venture-org-3",
    createdAt: "2023-11-15T14:00:00Z",
    images: ["/diverse-construction-team.png"],
    tags: ["platform", "collaboration", "digital", "revenue-sharing"],
    status: "available",
  },
]

export const mockResourcesData = [
  {
    id: "r1",
    name: "Gardening Tools Set",
    description: "Complete set of gardening tools including shovel, rake, pruners, and gloves.",
    category: "Tools",
    ownerId: "user1",
    createdAt: "2023-04-15T10:30:00Z",
    tags: ["gardening", "tools", "outdoor"],
    image: "/gardening-tools-set.png",
  },
  {
    id: "r2",
    name: "Projector",
    description: "HD projector with HDMI and USB connections. Great for presentations and movie nights.",
    category: "Electronics",
    ownerId: "user1",
    createdAt: "2023-04-10T14:45:00Z",
    tags: ["electronics", "entertainment", "presentations"],
    image: "/projector.png",
  },
  {
    id: "r3",
    name: "Professional Camera",
    description: "Canon EOS 5D Mark IV with 24-70mm lens.",
    category: "Photography",
    ownerId: "user3",
    createdAt: "2023-04-05T09:15:00Z",
    tags: ["photography", "equipment", "creative"],
    image: "/professional-camera.png",
  },
  {
    id: "r4",
    name: "Camping Tent (4-person)",
    description: "Weatherproof 4-person tent, easy to set up and pack away.",
    category: "Outdoor",
    ownerId: "user2",
    createdAt: "2023-03-28T16:20:00Z",
    tags: ["camping", "outdoor", "adventure"],
    image: "/camping-tent.png",
  },
  {
    id: "r5",
    name: "Electric Keyboard",
    description: "88-key weighted keyboard with stand and sustain pedal.",
    category: "Music",
    ownerId: "user4",
    createdAt: "2023-03-20T11:00:00Z",
    tags: ["music", "instrument", "creative"],
    image: "/electric-keyboard.png",
  },
  {
    id: "r6",
    name: "Electric Drill and Bit Set",
    description: "Cordless electric drill with various bits for home improvement projects.",
    category: "Tools",
    ownerId: "user6",
    createdAt: "2023-03-15T13:30:00Z",
    tags: ["tools", "diy", "home improvement"],
    image: "/electric-drill.png",
  },
]

export const mockSkillsData = [
  {
    id: "s1",
    name: "Carpentry",
    description: "Building and repairing wooden structures and furniture.",
    category: "Crafts",
    level: "advanced",
    ownerId: "user1",
    createdAt: "2023-04-15T10:30:00Z",
    tags: ["woodworking", "construction", "diy"],
  },
  {
    id: "s2",
    name: "Web Development",
    description: "Creating websites and web applications using HTML, CSS, JavaScript, and various frameworks.",
    category: "Technology",
    level: "expert",
    ownerId: "user2",
    createdAt: "2023-04-10T14:45:00Z",
    tags: ["coding", "technology", "design"],
  },
  {
    id: "s3",
    name: "Cooking",
    description: "Preparing various cuisines with a focus on vegetarian and vegan options.",
    category: "Food",
    level: "intermediate",
    ownerId: "user3",
    createdAt: "2023-04-05T09:15:00Z",
    tags: ["food", "culinary", "nutrition"],
  },
  {
    id: "s4",
    name: "Gardening",
    description: "Growing vegetables, herbs, and maintaining ornamental plants.",
    category: "Outdoor",
    level: "advanced",
    ownerId: "user4",
    createdAt: "2023-03-28T16:20:00Z",
    tags: ["plants", "outdoor", "sustainability"],
  },
  {
    id: "s5",
    name: "Graphic Design",
    description: "Creating visual content for digital and print media.",
    category: "Creative",
    level: "expert",
    ownerId: "user5",
    createdAt: "2023-03-20T11:00:00Z",
    tags: ["design", "creative", "digital"],
  },
  {
    id: "s6",
    name: "Yoga Instruction",
    description: "Teaching various yoga styles for all levels.",
    category: "Fitness",
    level: "advanced",
    ownerId: "user6",
    createdAt: "2023-03-15T13:30:00Z",
    tags: ["fitness", "wellness", "health"],
  },
  {
    id: "s7",
    name: "Spanish Language",
    description: "Teaching conversational Spanish for beginners to intermediate learners.",
    category: "Education",
    level: "expert",
    ownerId: "user7",
    createdAt: "2023-03-10T15:45:00Z",
    tags: ["language", "education", "communication"],
  },
]

export function getResourceById(id: string) {
  return mockResourcesData.find((resource) => resource.id === id)
}

export function getSkillById(id: string) {
  return mockSkillsData.find((skill) => skill.id === id)
}

export function getResourcesByOwnerId(ownerId: string) {
  return mockResourcesData.filter((resource) => resource.ownerId === ownerId)
}

export function getSkillsByOwnerId(ownerId: string) {
  return mockSkillsData.filter((skill) => skill.ownerId === ownerId)
}

export function getGroupMarketplaceListingsByGroupId(groupId: string) {
  return mockGroupMarketplaceListings.filter((listing) => listing.groupId === groupId)
}
