export interface Task {
  id: string
  name: string
  description: string
  points: number
  completed: boolean
  status: 'not_started' | 'in_progress' | 'awaiting_approval' | 'completed' | 'rejected'
  assignedTo?: string
  requiredBadge?: string
  estimatedTime: string
}

export interface JobShift {
  id: string
  title: string
  description: string
  groupId: string
  createdBy: string
  category: string
  location: string
  duration: string
  totalPoints: number
  priority: "low" | "medium" | "high"
  status: "open" | "in-progress" | "completed" | "cancelled"
  requiredBadges: string[]
  tasks: Task[]
  assignees: string[]
  maxAssignees: number
  deadline?: string
  createdAt: string
  updatedAt: string
  comments: Array<{
    id: string
    userId: string
    content: string
    createdAt: string
    replies?: Array<{
      id: string
      userId: string
      content: string
      createdAt: string
    }>
  }>
}

export const mockJobShifts: JobShift[] = [
  {
    id: "shift1",
    title: "Garden Coordinator - Community Garden Workday",
    description: "Lead and coordinate the Community Garden Workday at Pachamama Farm, managing teams and ensuring project objectives are met.",
    groupId: "group1",
    createdBy: "user1",
    category: "Environment",
    location: "Pachamama Farm, Boulder, CO",
    duration: "4 hours",
    totalPoints: 65,
    priority: "high",
    status: "open",
    requiredBadges: ["plant-steward", "event-coordinator"],
    maxAssignees: 2,
    assignees: ["user1"],
    deadline: "2025-07-15T14:00:00Z",
    createdAt: "2024-01-15T09:00:00Z",
    updatedAt: "2024-01-15T09:00:00Z",
    tasks: [
      {
        id: "task1",
        name: "Setup Workday Stations",
        description: "Set up tool stations, water access points, and work area assignments",
        points: 15,
        completed: false,
        status: "not_started",
        assignedTo: "user1",
        requiredBadge: "event-coordinator",
        estimatedTime: "45 minutes",
      },
      {
        id: "task2",
        name: "Coordinate Planting Teams",
        description: "Direct teams for new bed preparation and plantings",
        points: 25,
        completed: false,
        status: "not_started",
        estimatedTime: "2 hours",
      },
      {
        id: "task3",
        name: "Lead Educational Session",
        description: "Conduct brief educational session on sustainable gardening practices",
        points: 25,
        completed: false,
        status: "not_started",
        assignedTo: "user1",
        requiredBadge: "plant-steward",
        estimatedTime: "1 hour",
      },
    ],
    comments: [
      {
        id: "comment1",
        userId: "user3",
        content: "Great initiative! I'd love to help with the harvesting.",
        createdAt: "2024-01-15T10:30:00Z",
        replies: [
          {
            id: "reply1",
            userId: "user1",
            content: "Thanks! Feel free to sign up for the harvest task.",
            createdAt: "2024-01-15T11:00:00Z",
          },
        ],
      },
    ],
  },
  {
    id: "shift2",
    title: "Garden Maintenance Team - Community Garden Workday",
    description: "Hands-on garden maintenance work including weeding, watering, harvesting, and general upkeep at Pachamama Farm.",
    groupId: "group1",
    createdBy: "user3",
    category: "Environment",
    location: "Pachamama Farm, Boulder, CO",
    duration: "4 hours",
    totalPoints: 50,
    priority: "high",
    status: "open",
    requiredBadges: ["plant-steward"],
    maxAssignees: 8,
    assignees: ["user1", "user3", "u5"],
    deadline: "2025-07-18T10:00:00Z",
    createdAt: "2024-01-14T14:00:00Z",
    updatedAt: "2024-01-14T14:00:00Z",
    tasks: [
      {
        id: "task4",
        name: "Weed Existing Garden Beds",
        description: "Remove weeds from all established garden beds and pathways",
        points: 15,
        completed: false,
        status: "not_started",
        requiredBadge: "plant-steward",
        estimatedTime: "1.5 hours",
      },
      {
        id: "task5",
        name: "Water Garden Areas",
        description: "Deep watering of all garden sections and newly planted areas",
        points: 15,
        completed: false,
        status: "not_started",
        estimatedTime: "1 hour",
      },
      {
        id: "task6",
        name: "Harvest Ready Crops",
        description: "Harvest vegetables and herbs that are ready for collection",
        points: 20,
        completed: false,
        status: "not_started",
        requiredBadge: "plant-steward",
        estimatedTime: "1.5 hours",
      },
    ],
    comments: [
      {
        id: "comment2",
        userId: "user5",
        content: "This looks like a great learning opportunity! Do I need prior experience?",
        createdAt: "2024-01-14T15:00:00Z",
      },
    ],
  },
  {
    id: "shift3",
    title: "New Bed Construction - Community Garden Workday",
    description: "Build new raised garden beds and install irrigation infrastructure as part of the garden expansion at Pachamama Farm.",
    groupId: "group1",
    createdBy: "user4",
    category: "Environment",
    location: "Pachamama Farm, Boulder, CO",
    duration: "4 hours",
    totalPoints: 80,
    priority: "high",
    status: "open",
    requiredBadges: ["environmental-steward"],
    maxAssignees: 6,
    assignees: ["user1", "user4"],
    deadline: "2025-07-22T09:00:00Z",
    createdAt: "2024-01-12T11:00:00Z",
    updatedAt: "2024-01-16T09:00:00Z",
    tasks: [
      {
        id: "task7",
        name: "Prepare Bed Locations",
        description: "Clear and level ground for 5 new raised garden beds",
        points: 25,
        completed: false,
        status: "not_started",
        estimatedTime: "1.5 hours",
      },
      {
        id: "task8",
        name: "Assemble Raised Bed Frames",
        description: "Build wooden frames for new raised garden beds",
        points: 30,
        completed: false,
        status: "not_started",
        assignedTo: "user4",
        requiredBadge: "environmental-steward",
        estimatedTime: "2 hours",
      },
      {
        id: "task9",
        name: "Install Drip Irrigation Lines",
        description: "Set up drip irrigation system for water efficiency",
        points: 25,
        completed: false,
        status: "not_started",
        estimatedTime: "1.5 hours",
      },
    ],
    comments: [
      {
        id: "comment3",
        userId: "user8",
        content: "Setup is complete! Ready for the workshop tomorrow.",
        createdAt: "2024-01-16T16:00:00Z",
      },
    ],
  },
  {
    id: "shift4",
    title: "Bike Repair Station Maintenance",
    description:
      "Monthly maintenance of the community bike repair station including tool organization and basic repairs.",
    groupId: "group1",
    createdBy: "user9",
    category: "Transportation",
    location: "Bike Repair Station, Park Avenue",
    duration: "2 hours",
    totalPoints: 30,
    priority: "low",
    status: "open",
    requiredBadges: ["bike-mechanic"],
    maxAssignees: 2,
    assignees: [],
    deadline: "2024-01-30T15:00:00Z",
    createdAt: "2024-01-13T12:00:00Z",
    updatedAt: "2024-01-13T12:00:00Z",
    tasks: [
      {
        id: "task10",
        name: "Tool Inventory",
        description: "Check and organize all repair tools",
        points: 10,
        completed: false,
        status: "not_started",
        estimatedTime: "30 minutes",
      },
      {
        id: "task11",
        name: "Basic Bike Repairs",
        description: "Fix any bikes left for community repair",
        points: 20,
        completed: false,
        status: "not_started",
        requiredBadge: "bike-mechanic",
        estimatedTime: "1.5 hours",
      },
    ],
    comments: [],
  },
  {
    id: "shift5",
    title: "Community Composting System Setup",
    description: "Set up and organize the new community composting system behind the community center.",
    groupId: "group1",
    createdBy: "user10",
    category: "Environment",
    location: "Community Center Back Yard",
    duration: "5 hours",
    totalPoints: 100,
    priority: "high",
    status: "completed",
    requiredBadges: ["environmental-steward"],
    maxAssignees: 5,
    assignees: ["user2", "user3", "user11", "user12"],
    deadline: "2024-01-10T16:00:00Z",
    createdAt: "2024-01-05T10:00:00Z",
    updatedAt: "2024-01-10T17:00:00Z",
    tasks: [
      {
        id: "task12",
        name: "Assemble Compost Bins",
        description: "Build three large compost bins from provided materials",
        points: 40,
        completed: true,
        status: "completed",
        assignedTo: "user2",
        estimatedTime: "2 hours",
      },
      {
        id: "task13",
        name: "Create Signage",
        description: "Make educational signs about composting process",
        points: 25,
        completed: true,
        status: "completed",
        assignedTo: "user3",
        estimatedTime: "1.5 hours",
      },
      {
        id: "task14",
        name: "Initial Compost Setup",
        description: "Add initial brown and green materials to start composting",
        points: 35,
        completed: true,
        status: "completed",
        assignedTo: "user11",
        estimatedTime: "1.5 hours",
      },
    ],
    comments: [
      {
        id: "comment4",
        userId: "user12",
        content: "Amazing work everyone! The composting system looks fantastic.",
        createdAt: "2024-01-10T18:00:00Z",
      },
      {
        id: "comment5",
        userId: "user2",
        content: "Thanks! Can't wait to see it in full operation.",
        createdAt: "2024-01-10T18:30:00Z",
      },
    ],
  },
  {
    id: "shift5",
    title: "Community Kitchen Helper",
    description: "Assist with food prep and serving at the weekly community dinner.",
    groupId: "group2",
    createdBy: "user2",
    category: "Community",
    location: "Community Center Kitchen",
    duration: "3 hours",
    totalPoints: 45,
    priority: "medium",
    status: "open",
    requiredBadges: [],
    maxAssignees: 4,
    assignees: ["user1", "user2"],
    deadline: "2025-07-15T17:00:00Z",
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-10T09:00:00Z",
    tasks: [
      {
        id: "task15",
        name: "Food Preparation",
        description: "Help prepare vegetables and sides for community dinner",
        points: 20,
        completed: false,
        status: "not_started",
        estimatedTime: "2 hours",
      },
      {
        id: "task16",
        name: "Serving and Cleanup",
        description: "Serve dinner and help with kitchen cleanup",
        points: 25,
        completed: false,
        status: "not_started",
        estimatedTime: "1 hour",
      },
    ],
    comments: [],
  },
  {
    id: "shift6",
    title: "Solar Panel Cleaning Team",
    description: "Monthly cleaning and inspection of community solar panels on the center roof.",
    groupId: "venture-org-1",
    createdBy: "user3",
    category: "Energy",
    location: "Community Center Rooftop",
    duration: "2 hours",
    totalPoints: 40,
    priority: "medium",
    status: "open",
    requiredBadges: ["solar-tech"],
    maxAssignees: 3,
    assignees: ["user1"],
    deadline: "2025-07-15T08:00:00Z",
    createdAt: "2024-01-08T10:00:00Z",
    updatedAt: "2024-01-08T10:00:00Z",
    tasks: [
      {
        id: "task17",
        name: "Panel Inspection",
        description: "Visual inspection of all solar panels for damage",
        points: 15,
        completed: false,
        status: "not_started",
        estimatedTime: "30 minutes",
      },
      {
        id: "task18",
        name: "Panel Cleaning",
        description: "Clean all solar panels with appropriate equipment",
        points: 25,
        completed: false,
        status: "not_started",
        estimatedTime: "1.5 hours",
      },
    ],
    comments: [],
  },
  {
    id: "shift7",
    title: "Neighborhood Cleanup Coordinator",
    description: "Organize and lead the monthly neighborhood cleanup effort.",
    groupId: "group1",
    createdBy: "user4",
    category: "Environment",
    location: "Central Park Area",
    duration: "3 hours",
    totalPoints: 55,
    priority: "high",
    status: "in-progress",
    requiredBadges: ["event-coordinator"],
    maxAssignees: 2,
    assignees: ["user1"],
    deadline: "2025-07-19T09:00:00Z",
    createdAt: "2024-01-05T12:00:00Z",
    updatedAt: "2024-01-12T14:00:00Z",
    tasks: [
      {
        id: "task19",
        name: "Coordinate Volunteers",
        description: "Organize volunteer teams and assign cleanup areas",
        points: 20,
        completed: true,
        status: "completed",
        assignedTo: "user1",
        estimatedTime: "1 hour",
      },
      {
        id: "task20",
        name: "Lead Cleanup Activity",
        description: "Lead the actual cleanup and coordinate teams",
        points: 35,
        completed: false,
        status: "in_progress",
        assignedTo: "user1",
        estimatedTime: "2 hours",
      },
    ],
    comments: [
      {
        id: "comment6",
        userId: "user5",
        content: "Great organization! The volunteer turnout was amazing.",
        createdAt: "2024-01-12T15:00:00Z",
      },
    ],
  },
  {
    id: "shift8",
    title: "Food Hub Delivery Driver",
    description: "Deliver fresh produce from local farms to community pickup points.",
    groupId: "venture-org-2",
    createdBy: "user2",
    category: "Food",
    location: "Various Pickup Locations",
    duration: "4 hours",
    totalPoints: 60,
    priority: "medium",
    status: "open",
    requiredBadges: ["driver-certified"],
    maxAssignees: 2,
    assignees: ["user1"],
    deadline: "2025-07-19T18:00:00Z",
    createdAt: "2024-01-03T08:00:00Z",
    updatedAt: "2024-01-03T08:00:00Z",
    tasks: [
      {
        id: "task21",
        name: "Load Delivery Vehicle",
        description: "Load fresh produce and organize delivery route",
        points: 20,
        completed: false,
        status: "not_started",
        estimatedTime: "1 hour",
      },
      {
        id: "task22",
        name: "Complete Delivery Route",
        description: "Deliver to all scheduled pickup locations",
        points: 40,
        completed: false,
        status: "not_started",
        estimatedTime: "3 hours",
      },
    ],
    comments: [],
  },
  {
    id: "shift9",
    title: "Workshop: Sustainable Living",
    description: "Educational workshop on sustainable living practices for community members.",
    groupId: "group1",
    createdBy: "user5",
    category: "Education",
    location: "Community Center",
    duration: "2 hours",
    totalPoints: 35,
    priority: "medium",
    status: "open",
    requiredBadges: [],
    maxAssignees: 3,
    assignees: ["user1"],
    deadline: "2025-07-15T19:00:00Z",
    createdAt: "2024-01-01T08:00:00Z",
    updatedAt: "2024-01-01T08:00:00Z",
    tasks: [
      {
        id: "task23",
        name: "Setup Workshop Materials",
        description: "Prepare materials and setup presentation area",
        points: 15,
        completed: false,
        status: "not_started",
        estimatedTime: "30 minutes",
      },
      {
        id: "task24",
        name: "Lead Workshop Session",
        description: "Present workshop content and facilitate discussion",
        points: 20,
        completed: false,
        status: "not_started",
        estimatedTime: "1.5 hours",
      },
    ],
    comments: [],
  },
  {
    id: "shift10",
    title: "Community Dinner Setup",
    description: "Help set up tables, chairs, and decorations for the weekly community dinner.",
    groupId: "group2",
    createdBy: "user3",
    category: "Community",
    location: "Community Center",
    duration: "1.5 hours",
    totalPoints: 25,
    priority: "low",
    status: "open",
    requiredBadges: [],
    maxAssignees: 5,
    assignees: ["user1", "user3", "user4"],
    deadline: "2025-07-19T16:00:00Z",
    createdAt: "2024-01-01T10:00:00Z",
    updatedAt: "2024-01-01T10:00:00Z",
    tasks: [
      {
        id: "task25",
        name: "Arrange Tables and Chairs",
        description: "Set up dining area with tables and chairs for 50 people",
        points: 15,
        completed: false,
        status: "not_started",
        estimatedTime: "1 hour",
      },
      {
        id: "task26",
        name: "Decorate Space",
        description: "Add decorations and ambient lighting",
        points: 10,
        completed: false,
        status: "not_started",
        estimatedTime: "30 minutes",
      },
    ],
    comments: [],
  },
  {
    id: "shift11",
    title: "Evening Yoga Class",
    description: "Lead relaxing evening yoga session for community wellness.",
    groupId: "group1",
    createdBy: "user6",
    category: "Wellness",
    location: "Community Center - Yoga Studio",
    duration: "1 hour",
    totalPoints: 30,
    priority: "low",
    status: "open",
    requiredBadges: ["yoga-instructor"],
    maxAssignees: 1,
    assignees: ["user1"],
    deadline: "2025-07-19T20:00:00Z",
    createdAt: "2024-01-01T12:00:00Z",
    updatedAt: "2024-01-01T12:00:00Z",
    tasks: [
      {
        id: "task27",
        name: "Prepare Yoga Space",
        description: "Set up mats, props, and calming environment",
        points: 10,
        completed: false,
        status: "not_started",
        estimatedTime: "15 minutes",
      },
      {
        id: "task28",
        name: "Lead Yoga Session",
        description: "Guide participants through evening yoga practice",
        points: 20,
        completed: false,
        status: "not_started",
        estimatedTime: "45 minutes",
      },
    ],
    comments: [],
  },
]

export const mockBadges = [
  {
    id: "plant-steward",
    name: "Plant Steward",
    description: "Certified to care for community plants and gardens",
    emoji: "🌱",
    category: "Environmental",
    color: "green",
    requirements: [
      "Complete plant care workshop",
      "Demonstrate proper watering techniques",
      "Identify 10 common garden plants",
    ],
    holders: ["user2", "user3", "user11"],
    jobsUnlocked: ["Community Garden Maintenance", "Plant Care Tasks"],
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "solar-installer",
    name: "Solar Installer",
    description: "Qualified to install and maintain solar energy systems",
    emoji: "☀️",
    category: "Technical",
    color: "yellow",
    requirements: [
      "Complete solar installation training",
      "Pass electrical safety exam",
      "Assist with 2 installations",
    ],
    holders: ["user4", "user5"],
    jobsUnlocked: ["Solar Panel Installation", "Renewable Energy Projects"],
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "event-coordinator",
    name: "Event Coordinator",
    description: "Experienced in organizing and managing community events",
    emoji: "🎯",
    category: "Leadership",
    color: "purple",
    requirements: [
      "Organize 1 successful community event",
      "Complete event planning workshop",
      "Demonstrate leadership skills",
    ],
    holders: ["user6", "user7", "user8"],
    jobsUnlocked: ["Workshop Coordination", "Event Management"],
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "bike-mechanic",
    name: "Bike Mechanic",
    description: "Skilled in bicycle repair and maintenance",
    emoji: "🚲",
    category: "Technical",
    color: "blue",
    requirements: ["Complete bike repair workshop", "Fix 5 community bikes", "Demonstrate tool proficiency"],
    holders: ["user9"],
    jobsUnlocked: ["Bike Repair Station", "Transportation Projects"],
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "environmental-steward",
    name: "Environmental Steward",
    description: "Committed to environmental protection and sustainability",
    emoji: "🌍",
    category: "Environmental",
    color: "green",
    requirements: [
      "Complete environmental impact workshop",
      "Lead 1 sustainability project",
      "Demonstrate eco-friendly practices",
    ],
    holders: ["user2", "user10", "user11", "user12"],
    jobsUnlocked: ["Composting Projects", "Environmental Initiatives"],
    createdAt: "2024-01-01T00:00:00Z",
  },
  {
    id: "safety-certified",
    name: "Safety Certified",
    description: "Trained in workplace safety and emergency procedures",
    emoji: "🦺",
    category: "Safety",
    color: "orange",
    requirements: ["Complete safety training course", "Pass safety knowledge exam", "Demonstrate proper equipment use"],
    holders: ["user4", "user5", "user6"],
    jobsUnlocked: ["High-Risk Projects", "Construction Tasks"],
    createdAt: "2024-01-01T00:00:00Z",
  },
]
