import { type Voucher, type VoucherClaim, VoucherCategory, VoucherStatus } from "./types"

export const mockVouchers: Voucher[] = [
  {
    id: "voucher-1",
    title: "Home-cooked Meal for 4",
    description:
      "I'll cook a delicious vegetarian meal for your family. Specializing in Italian and Mediterranean cuisine.",
    category: VoucherCategory.Service,
    offeredBy: "user1",
    ringId: "ring1",
    createdAt: "2024-01-15T10:00:00Z",
    expiresAt: "2024-04-15T10:00:00Z",
    status: VoucherStatus.Available,
    tags: ["cooking", "vegetarian", "family"],
    estimatedValue: 80,
    timeCommitment: "3 hours",
    location: "My kitchen or yours",
    maxClaims: 3,
    currentClaims: 1,
  },
  {
    id: "voucher-2",
    title: "Garden Design Consultation",
    description: "I'll help you design a sustainable garden space, including plant selection and layout planning.",
    category: VoucherCategory.Skill,
    offeredBy: "user2",
    ringId: "ring1",
    createdAt: "2024-01-20T14:30:00Z",
    expiresAt: "2024-06-20T14:30:00Z",
    status: VoucherStatus.Available,
    tags: ["gardening", "sustainability", "design"],
    estimatedValue: 150,
    timeCommitment: "2 hours",
    location: "Your property",
    maxClaims: 5,
    currentClaims: 0,
  },
  {
    id: "voucher-3",
    title: "Handmade Pottery Bowl",
    description: "Beautiful ceramic bowl, perfect for serving or decoration. Glazed in earth tones.",
    category: VoucherCategory.Goods,
    offeredBy: "user3",
    ringId: "ring1",
    createdAt: "2024-01-25T09:15:00Z",
    status: VoucherStatus.Claimed,
    claimedBy: "user1",
    claimedAt: "2024-01-26T16:20:00Z",
    tags: ["pottery", "handmade", "ceramic"],
    estimatedValue: 45,
    location: "Pickup from my studio",
    maxClaims: 1,
    currentClaims: 1,
  },
  {
    id: "voucher-4",
    title: "Web Development Tutorial",
    description: "One-on-one session teaching HTML, CSS, and JavaScript basics. Perfect for beginners!",
    category: VoucherCategory.Skill,
    offeredBy: "user2",
    ringId: "ring1",
    createdAt: "2024-02-01T11:00:00Z",
    expiresAt: "2024-05-01T11:00:00Z",
    status: VoucherStatus.Available,
    tags: ["programming", "web development", "tutorial"],
    estimatedValue: 100,
    timeCommitment: "2 hours",
    location: "Online or in-person",
    maxClaims: 4,
    currentClaims: 2,
  },
  {
    id: "voucher-5",
    title: "Bike Repair Service",
    description: "I'll fix your bike! Basic repairs, tune-ups, and maintenance. Bring your own parts if needed.",
    category: VoucherCategory.Service,
    offeredBy: "user4",
    ringId: "ring1",
    createdAt: "2024-02-05T16:45:00Z",
    expiresAt: "2024-08-05T16:45:00Z",
    status: VoucherStatus.Available,
    tags: ["bike repair", "maintenance", "cycling"],
    estimatedValue: 60,
    timeCommitment: "1-2 hours",
    location: "My garage workshop",
    maxClaims: 10,
    currentClaims: 3,
  },
  {
    id: "voucher-6",
    title: "Meditation & Mindfulness Session",
    description: "Guided meditation session for stress relief and mindfulness practice. Suitable for all levels.",
    category: VoucherCategory.Experience,
    offeredBy: "u5",
    ringId: "ring1",
    createdAt: "2024-02-10T08:30:00Z",
    expiresAt: "2024-05-10T08:30:00Z",
    status: VoucherStatus.Available,
    tags: ["meditation", "wellness", "mindfulness"],
    estimatedValue: 40,
    timeCommitment: "1 hour",
    location: "Community center or online",
    maxClaims: 8,
    currentClaims: 1,
  },
  {
    id: "voucher-7",
    title: "Fresh Herbs from Garden",
    description: "Seasonal herbs from my organic garden: basil, rosemary, thyme, oregano, and more!",
    category: VoucherCategory.Goods,
    offeredBy: "user3",
    ringId: "ring1",
    createdAt: "2024-02-12T12:00:00Z",
    expiresAt: "2024-09-12T12:00:00Z",
    status: VoucherStatus.Available,
    tags: ["herbs", "organic", "gardening"],
    estimatedValue: 15,
    location: "Pickup from my garden",
    maxClaims: 20,
    currentClaims: 5,
  },
  {
    id: "voucher-8",
    title: "Photography Session",
    description: "Professional portrait or event photography session. Digital copies included.",
    category: VoucherCategory.Service,
    offeredBy: "user1",
    ringId: "ring1",
    createdAt: "2024-02-15T13:20:00Z",
    status: VoucherStatus.Completed,
    claimedBy: "user2",
    claimedAt: "2024-02-16T10:00:00Z",
    completedAt: "2024-02-20T15:30:00Z",
    tags: ["photography", "portraits", "events"],
    estimatedValue: 200,
    timeCommitment: "2-3 hours",
    location: "Flexible",
    maxClaims: 1,
    currentClaims: 1,
  },
]

export const mockVoucherClaims: VoucherClaim[] = [
  {
    id: "claim-1",
    voucherId: "voucher-3",
    claimedBy: "user1",
    claimedAt: "2024-01-26T16:20:00Z",
    status: "completed",
    completedAt: "2024-01-28T14:00:00Z",
    rating: 5,
    feedback: "Beautiful bowl! Exactly as described and perfect for my kitchen.",
  },
  {
    id: "claim-2",
    voucherId: "voucher-8",
    claimedBy: "user2",
    claimedAt: "2024-02-16T10:00:00Z",
    status: "completed",
    completedAt: "2024-02-20T15:30:00Z",
    rating: 5,
    feedback: "Amazing photos! Cameron really captured the essence of our family gathering.",
  },
  {
    id: "claim-3",
    voucherId: "voucher-1",
    claimedBy: "user4",
    claimedAt: "2024-02-18T19:30:00Z",
    status: "accepted",
    notes: "Looking forward to the meal this weekend!",
  },
  {
    id: "claim-4",
    voucherId: "voucher-4",
    claimedBy: "user3",
    claimedAt: "2024-02-20T11:15:00Z",
    status: "pending",
    notes: "Would love to learn web development basics. Available weekends.",
  },
]

export const getVouchersByRingId = (ringId: string): Voucher[] => {
  return mockVouchers.filter((voucher) => voucher.ringId === ringId)
}

export const getVoucherClaimsByVoucherId = (voucherId: string): VoucherClaim[] => {
  return mockVoucherClaims.filter((claim) => claim.voucherId === voucherId)
}

export const getVouchersByUserId = (userId: string): Voucher[] => {
  return mockVouchers.filter((voucher) => voucher.offeredBy === userId)
}

export const getClaimedVouchersByUserId = (userId: string): VoucherClaim[] => {
  return mockVoucherClaims.filter((claim) => claim.claimedBy === userId)
}
